on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pages build
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: Setup Pages
        run: |
          mkdir -p _data
          cat > _data/github.yml <<EOF
          build_revision: ${{ github.sha }}
          owner_url: ${{ github.server_url }}/${{ github.repository_owner }}
          owner_name: ${{ github.repository_owner }}
          EOF

      - name: Build site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Lint gems
        run: bundle exec rubocop -D --config .rubocop.yml

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
